name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # Running at midnight every Sunday (to preserve caches mostly)

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      
    runs-on: ubuntu-latest

    env:
      CAKE_VERSION: "v2419"

    steps:
      - name: Restore Cake Cache
        id: cake-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: $HOME/cake-x64-64
          key: ${{ runner.OS }}-CAKE-${{ env.CAKE_VERSION }}

      - name: Build Cake
        run: |
          cd $HOME
          wget https://github.com/CakeML/cakeml/releases/download/${{ env.CAKE_VERSION }}/cake-x64-64.tar.gz
          tar -xvf cake-x64-64.tar.gz
          cd $HOME/cake-x64-64
          make cake
      
      - name: Cake Cache Save
        id: cake-cache-install
        if: steps.cake-cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: $HOME/cake
          key: ${{ runner.OS }}-CAKE-${{ env.CAKE_VERSION }}

      - name: Install Cake
        run:
          sudo ln -s $HOME/cake-x64-64/cake /usr/bin


############### Final Testing Checkout and Build am-cakeml
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Build
        run: |
          cd ${{ github.workspace }}/tests
          make ci