name: Make Release

on:
  workflow_dispatch:
    inputs:
      tag_string:
        description: 'Release version'
        required: true
        type: string
        default: 'v*.*.*'
      draft:
        description: 'Is this a draft release?'
        required: false
        type: boolean
        default: false
      prerelease:
        description: 'Is this a pre-release version?'
        required: false
        type: boolean
        default: false

jobs:
  # Build and Test to make sure we put out a good release
  build_and_test:
    uses: ./.github/workflows/build_and_test.yaml

  release:
    runs-on: ubuntu-latest

    needs: build_and_test

    steps:
      - name: Download Release Binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: ${{ github.workspace }}
      
      - name: Extract Binaries
        run: |
          cd ${{ github.workspace }}
          tar -xvf bin.tar
          rm bin.tar

## Doing the complicated part of the release management
      - name: Create Tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{ inputs.tag_string }}`,
              sha: context.sha
            })

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: "Release of MAESTRO executables built for x64 Linux"
          files: bin/*
          fail_on_unmatched_files: true
          prerelease: ${{ inputs.prerelease }}
          draft: ${{ inputs.draft }}
          tag_name: refs/tags/${{ inputs.tag_string }}
          generate_release_notes: true
          name: ${{ github.ref_name }} Release

  
