name: Make Release

on:
  workflow_call:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # Build and Test to make sure we put out a good release
  build_and_test:
    uses: ./.github/workflows/build_and_test.yaml

  release:
    runs-on: ubuntu-latest

    needs: build_and_test

    steps:
      - name: Download Release Binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: ${{ github.workspace }}
      
      - name: Extract Binaries
        run: |
          cd ${{ github.workspace }}
          tar -xvf bin.tar
          rm bin.tar

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: "Release of MAESTRO executables built for x64 Linux"
          files: bin/*
          fail_on_unmatched_files: true
          prerelease: false
          draft: true
          generate_release_notes: true
          name: ${{ github.ref_name }} Release

  
