name: Make Release

on:
  workflow_dispatch:
    inputs:
      tag_string:
        description: 'Release version'
        required: true
        type: string
        default: 'v*.*.*'
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  # Build and Test to make sure we put out a good release
  build_and_test:
    uses: ./.github/workflows/build_and_test.yaml

  release:
    runs-on: ubuntu-latest

    needs: build_and_test

    steps:
      - name: Download Release Binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: ${{ github.workspace }}
      
      - name: Extract Binaries
        run: |
          cd ${{ github.workspace }}
          tar -xvf bin.tar
          rm bin.tar

## Doing the complicated part of the release management
########## If we a dispatch, then we checkout and create a new tag for the release
      - name: Checkout code
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4

      - name: Create a new tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd ${{ github.workspace }}
          git tag -a ${{ inputs.tag_string }} -m "Release ${{ inputs.tag_string }}"
          git push --tags

########## Otherwise we are just building the release
      - name: Create Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          body: "Release of MAESTRO executables built for x64 Linux"
          files: bin/*
          fail_on_unmatched_files: true
          prerelease: false
          draft: false
          generate_release_notes: true
          name: ${{ github.ref_name }} Release

  
